name: Create pull request for new branch

on:
  create

jobs:
  auto-pull-request:
    name: PullRequestAction
    runs-on: ubuntu-latest 
    steps:
      - name: Get branch name
        id: get-branch
        run: |
          echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
        shell: bash      
      - name: Create pull request
        id: open-pr
        uses: repo-sync/pull-request@v2 
        with:
            destination_branch: "main"
            pr_title: "feat: PLACEHOLDER TITLE"
            pr_draft: true